<?php

namespace Database\Seeders;

use App\Models\AktivitasKpiK3;
use Illuminate\Database\Seeder;

class AktivitasKpiK3Seeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'kode' => 'C.1',
                'nama_aktivitas' => 'Laporan Inspeksi Peralatan',
                'kompleksitas' => 2,
                'frekuensi' => 1,
                'skor' => 2 * 1, // <-- Diset langsung
                'target_per_bulan' => 2,
                'ikut_hari_kerja' => true,
                'maks_per_hari' => 1,
                'mulai_berlaku' => 2026,
                'akhir_berlaku' => null,
                'safety' => true,
                'pengawas' => false,
                'medis' => false,
                'status' => 'AKTIF',
            ],
            [
                'kode' => 'C.2',
                'nama_aktivitas' => 'Laporan Temuan UA/UC',
                'kompleksitas' => 2,
                'frekuensi' => 3,
                'skor' => 2 * 3,
                'target_per_bulan' => 12,
                'ikut_hari_kerja' => true,
                'maks_per_hari' => 1,
                'mulai_berlaku' => 2026,
                'akhir_berlaku' => null,
                'safety' => true,
                'pengawas' => false,
                'medis' => false,
                'status' => 'AKTIF',
            ],
            [
                'kode' => 'C.4',
                'nama_aktivitas' => 'Laporan OBSERI',
                'kompleksitas' => 2,
                'frekuensi' => 3,
                'skor' => 2 * 3,
                'target_per_bulan' => 20,
                'ikut_hari_kerja' => true,
                'maks_per_hari' => 1,
                'mulai_berlaku' => 2026,
                'akhir_berlaku' => null,
                'safety' => true,
                'pengawas' => false,
                'medis' => false,
                'status' => 'AKTIF',
            ],
            [
                'kode' => 'C.5',
                'nama_aktivitas' => 'Laporan Safety Permit',
                'kompleksitas' => 3,
                'frekuensi' => 2,
                'skor' => 3 * 2,
                'target_per_bulan' => 4,
                'ikut_hari_kerja' => true,
                'maks_per_hari' => 1,
                'mulai_berlaku' => 2026,
                'akhir_berlaku' => null,
                'safety' => true,
                'pengawas' => false,
                'medis' => false,
                'status' => 'AKTIF',
            ],
            [
                'kode' => 'D.1',
                'nama_aktivitas' => 'Laporan / Pelaporan Nearmiss',
                'kompleksitas' => 3,
                'frekuensi' => 1,
                'skor' => 3 * 1,
                'target_per_bulan' => 2,
                'ikut_hari_kerja' => true,
                'maks_per_hari' => 1,
                'mulai_berlaku' => 2026,
                'akhir_berlaku' => null,
                'safety' => true,
                'pengawas' => true,
                'medis' => false,
                'status' => 'AKTIF',
            ],
            [
                'kode' => 'D.2',
                'nama_aktivitas' => 'Laporan / Pelaporan Safety Briefing',
                'kompleksitas' => 1,
                'frekuensi' => 2,
                'skor' => 1 * 2,
                'target_per_bulan' => 4,
                'ikut_hari_kerja' => true,
                'maks_per_hari' => 1,
                'mulai_berlaku' => 2026,
                'akhir_berlaku' => null,
                'safety' => true,
                'pengawas' => true,
                'medis' => false,
                'status' => 'AKTIF',
            ],
            [
                'kode' => 'D.3',
                'nama_aktivitas' => 'Laporan Reward / Punishment',
                'kompleksitas' => 2,
                'frekuensi' => 2,
                'skor' => 2 * 2,
                'target_per_bulan' => 4,
                'ikut_hari_kerja' => true,
                'maks_per_hari' => 1,
                'mulai_berlaku' => 2026,
                'akhir_berlaku' => null,
                'safety' => true,
                'pengawas' => false,
                'medis' => false,
                'status' => 'AKTIF',
            ],
            [
                'kode' => 'D.4',
                'nama_aktivitas' => 'Laporan Sosialisasi Keselamatan Kerja',
                'kompleksitas' => 2,
                'frekuensi' => 1,
                'skor' => 2 * 1,
                'target_per_bulan' => 1,
                'ikut_hari_kerja' => false,
                'maks_per_hari' => 1,
                'mulai_berlaku' => 2026,
                'akhir_berlaku' => null,
                'safety' => true,
                'pengawas' => false,
                'medis' => false,
                'status' => 'AKTIF',
            ],
            [
                'kode' => 'E.1',
                'nama_aktivitas' => 'Laporan DCU',
                'kompleksitas' => 1,
                'frekuensi' => 3,
                'skor' => 1 * 3,
                'target_per_bulan' => 20,
                'ikut_hari_kerja' => true,
                'maks_per_hari' => 1,
                'mulai_berlaku' => 2026,
                'akhir_berlaku' => null,
                'safety' => true,
                'pengawas' => false,
                'medis' => true,
                'status' => 'AKTIF',
            ],
            [
                'kode' => 'E.2',
                'nama_aktivitas' => 'Laporan Bugar Sehat',
                'kompleksitas' => 1,
                'frekuensi' => 2,
                'skor' => 1 * 2,
                'target_per_bulan' => 1,
                'ikut_hari_kerja' => false,
                'maks_per_hari' => 1,
                'mulai_berlaku' => 2026,
                'akhir_berlaku' => null,
                'safety' => true,
                'pengawas' => false,
                'medis' => false,
                'status' => 'AKTIF',
            ],
            [
                'kode' => 'E.4',
                'nama_aktivitas' => 'Laporan Evaluasi Fatigue',
                'kompleksitas' => 2,
                'frekuensi' => 1,
                'skor' => 2 * 1,
                'target_per_bulan' => 1,
                'ikut_hari_kerja' => false,
                'maks_per_hari' => 1,
                'mulai_berlaku' => 2026,
                'akhir_berlaku' => null,
                'safety' => false,
                'pengawas' => false,
                'medis' => true,
                'status' => 'AKTIF',
            ],
            [
                'kode' => 'E.5',
                'nama_aktivitas' => 'Laporan Sosialisasi Kesehatan Kerja',
                'kompleksitas' => 2,
                'frekuensi' => 1,
                'skor' => 2 * 1,
                'target_per_bulan' => 1,
                'ikut_hari_kerja' => false,
                'maks_per_hari' => 1,
                'mulai_berlaku' => 2026,
                'akhir_berlaku' => null,
                'safety' => true,
                'pengawas' => false,
                'medis' => true,
                'status' => 'AKTIF',
            ],
            [
                'kode' => 'E.6',
                'nama_aktivitas' => 'Laporan Inspeksi Kotak P3K',
                'kompleksitas' => 1,
                'frekuensi' => 2,
                'skor' => 1 * 2,
                'target_per_bulan' => 4,
                'ikut_hari_kerja' => true,
                'maks_per_hari' => 1,
                'mulai_berlaku' => 2026,
                'akhir_berlaku' => null,
                'safety' => true,
                'pengawas' => false,
                'medis' => false,
                'status' => 'AKTIF',
            ],
        ];

        foreach ($data as $row) {
            AktivitasKpiK3::updateOrCreate(
                ['kode' => $row['kode']],
                $row
            );
        }
    }
}
