<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\StokAPD;
use App\Models\StokApdKode;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class StokApdSeeder extends Seeder
{
    public function run(): void
    {
        $listKodeOk = [
            '278',
            '119',
            '3001',
            '999',
            '96',
            '36',
            '104',
            '713',
            '777',
            '9113',
            '39',
            '66',
            '121',
            '43',
            '120',
            '24',
            '69',
            '492',
            '127',
            '60',
            '211',
            '133',
            '44',
            '92',
            '110',
            '3011',
            '10',
            '79',
            '1026',
            '9402',
            '9120',
            '14',
            '9117',
            '9112',
            '707',
            '112',
            '4',
            '91',
            '744',
            '107',
            '122',
            '276',
            '126',
            'PCS 05',
            '41',
            '29',
            '61',
            'PCS15',
            'PCS14',
            '16',
            'PCS12',
            '84',
            'PCS13',
            '2',
            '20',
            '88',
            '55',
            '12',
            '58',
            '9301',
            '128',
            '17',
            '1101',
            '15',
            '712',
            '9303',
            '1251',
            '73',
            '131',
            '21',
            '23',
            '101',
            '3012',
            '34',
            '124',
            '64',
            '28',
            '5',
            '6004',
            'PCS 14',
            '1161',
            '331',
            '27',
            '62',
            '22',
            '48',
            '46',
            '76',
            '117',
            '6006',
            'PCS 22',
            '31',
            '5003',
            '13',
            '1083',
            '369',
            '642',
            '47',
            'PCS 06',
            '1021',
            '207',
            '3000',
            '86',
            '37',
            '9114',
            'PCS 24',
            '82',
            '45',
            '9002',
            '74',
            '90',
            '109',
            '115',
            '1141',
            '70',
            '277',
            '99',
            '114',
            '98',
            '1',
            '118',
            '111',
            '123',
            '72',
            '78',
            '130',
            '129',
            '33',
            '77',
            '1051',
            '780',
            '71',
            '241',
            '83',
            '9304',
            '#N/A',
            '9302',
            'PCS01',
            '231',
            '3',
            '701',
            '25',
            '9115',
            '105',
            '1022',
            '100',
            '125',
            '203',
            '220',
            '261',
            '6',
            '26',
            '42',
            '998',
            '421',
            '106',
            '103',
            'PCS 04',
            '1231',
            '108',
            'PCS06',
            '102',
            '75',
            '714',
            '981',
            '1072',
            '700',
            '501',
            '9001',
            '279',
            '9305',
            'PCS04',
            '30',
            '9102',
            '40',
            '1081',
            'PCS 01',
            '711',
            '753',
            '1082',
            '113',
            '132',
            '93',
            '97',
            '771',
            '752',
            '282',
            '778',
            'PCS05',
            '9100',
            'PCS 02',
            'PCS 12',
            'PCS 11',
            'PCS 13',
            'PCS 15',
            'PCS 23'
        ];

        $daftarApd = [
            // --- KATEGORI WAJIB ---
            [
                'jenis_apd' => 'Helm Safety',
                'kategori' => 'WAJIB',
                'tipe_ukuran' => 'UNIVERSAL',
                'merk_rekomendasi' => 'MSA V-Gard',
                'ukuran_tersedia' => 'Universal',
                'harga_satuan' => 125000.00,
                'masa_pakai' => '5 tahun',
            ],
            [
                'jenis_apd' => 'Sepatu Safety',
                'kategori' => 'WAJIB',
                'tipe_ukuran' => 'ANGKA',
                'merk_rekomendasi' => 'Cheetah',
                'ukuran_tersedia' => '38-45',
                'harga_satuan' => 350000.00,
                'masa_pakai' => '1 tahun',
            ],
            [
                'jenis_apd' => 'Rompi Hi-Vis',
                'kategori' => 'WAJIB',
                'tipe_ukuran' => 'HURUF',
                'merk_rekomendasi' => 'Gosave',
                'ukuran_tersedia' => 'M, L, XL',
                'harga_satuan' => 45000.00,
                'masa_pakai' => '6 bulan',
            ],
            [
                'jenis_apd' => 'Sarung Tangan Kulit',
                'kategori' => 'WAJIB',
                'tipe_ukuran' => 'UNIVERSAL',
                'merk_rekomendasi' => 'Blue Eagle',
                'ukuran_tersedia' => 'Universal',
                'harga_satuan' => 60000.00,
                'masa_pakai' => '3 bulan',
            ],
            [
                'jenis_apd' => 'Kacamata Safety',
                'kategori' => 'WAJIB',
                'tipe_ukuran' => 'UNIVERSAL',
                'merk_rekomendasi' => 'King\'s',
                'ukuran_tersedia' => 'Universal',
                'harga_satuan' => 35000.00,
                'masa_pakai' => '6 bulan',
            ],
            [
                'jenis_apd' => 'Masker N95',
                'kategori' => 'WAJIB',
                'tipe_ukuran' => 'UNIVERSAL',
                'merk_rekomendasi' => '3M 8210',
                'ukuran_tersedia' => 'Universal',
                'harga_satuan' => 15000.00,
                'masa_pakai' => 'Sekali pakai',
            ],
            [
                'jenis_apd' => 'Masker Respirator',
                'kategori' => 'WAJIB',
                'tipe_ukuran' => 'HURUF',
                'merk_rekomendasi' => '3M Half Facepiece',
                'ukuran_tersedia' => 'S, M, L',
                'harga_satuan' => 250000.00,
                'masa_pakai' => '2 tahun',
            ],
            [
                'jenis_apd' => 'Earplug/Earmuff',
                'kategori' => 'WAJIB',
                'tipe_ukuran' => 'UNIVERSAL',
                'merk_rekomendasi' => 'Howard Leight',
                'ukuran_tersedia' => 'Universal',
                'harga_satuan' => 120000.00,
                'masa_pakai' => '1 tahun',
            ],
            [
                'jenis_apd' => 'Full Body Harness',
                'kategori' => 'WAJIB',
                'tipe_ukuran' => 'UNIVERSAL',
                'merk_rekomendasi' => 'Petzl',
                'ukuran_tersedia' => 'Universal',
                'harga_satuan' => 850000.00,
                'masa_pakai' => '5 tahun',
            ],
            [
                'jenis_apd' => 'Wearpack',
                'kategori' => 'WAJIB',
                'tipe_ukuran' => 'HURUF',
                'merk_rekomendasi' => 'IMJ',
                'ukuran_tersedia' => 'S, M, L, XL, XXL',
                'harga_satuan' => 220000.00,
                'masa_pakai' => '1 tahun',
            ],

            // --- KATEGORI KHUSUS (Tanda Merah di Gambar) ---
            [
                'jenis_apd' => 'SCBA',
                'kategori' => 'KHUSUS',
                'tipe_ukuran' => 'UNIVERSAL',
                'merk_rekomendasi' => 'Dräger',
                'ukuran_tersedia' => 'Universal',
                'harga_satuan' => 15000000.00,
                'masa_pakai' => '10 tahun',
            ],
            [
                'jenis_apd' => 'Pakaian FR',
                'kategori' => 'KHUSUS',
                'tipe_ukuran' => 'HURUF',
                'merk_rekomendasi' => 'Nomex',
                'ukuran_tersedia' => 'M, L, XL',
                'harga_satuan' => 1200000.00,
                'masa_pakai' => '3 tahun',
            ],
            [
                'jenis_apd' => 'Chemical Suit',
                'kategori' => 'KHUSUS',
                'tipe_ukuran' => 'HURUF',
                'merk_rekomendasi' => 'Tyvek',
                'ukuran_tersedia' => 'L, XL',
                'harga_satuan' => 450000.00,
                'masa_pakai' => 'Sekali pakai',
            ],
            [
                'jenis_apd' => 'Sarung Tangan Listrik',
                'kategori' => 'KHUSUS',
                'tipe_ukuran' => 'ANGKA',
                'merk_rekomendasi' => 'Regeltex',
                'ukuran_tersedia' => '8, 9, 10, 11',
                'harga_satuan' => 750000.00,
                'masa_pakai' => '1 tahun',
            ],
            [
                'jenis_apd' => 'Face Shield',
                'kategori' => 'KHUSUS',
                'tipe_ukuran' => 'UNIVERSAL',
                'merk_rekomendasi' => 'Blue Eagle',
                'ukuran_tersedia' => 'Universal',
                'harga_satuan' => 85000.00,
                'masa_pakai' => '2 tahun',
            ],
            [
                'jenis_apd' => 'Kacamata Las',
                'kategori' => 'KHUSUS',
                'tipe_ukuran' => 'UNIVERSAL',
                'merk_rekomendasi' => 'Krisbow',
                'ukuran_tersedia' => 'Universal',
                'harga_satuan' => 120000.00,
                'masa_pakai' => '2 tahun',
            ],
            [
                'jenis_apd' => 'Knee Pad',
                'kategori' => 'KHUSUS',
                'tipe_ukuran' => 'UNIVERSAL',
                'merk_rekomendasi' => 'Ergodyne',
                'ukuran_tersedia' => 'Universal',
                'harga_satuan' => 150000.00,
                'masa_pakai' => '1 tahun',
            ],
        ];

        DB::beginTransaction();
        try {
            $isFirstItem = true;

            foreach ($daftarApd as $data) {
                // Generate data random logis untuk stok
                $stokAwal = rand(50, 200);
                $digunakan = rand(10, 40);
                $rusak = rand(0, 5);

                $apd = StokAPD::create([
                    'kode_apd'           => StokAPD::generateKode($data['jenis_apd']),
                    'gambar_apd'         => 'apd_images/Purple-Dark-mode-desktop-wallpaper.png',
                    'jenis_apd'          => $data['jenis_apd'],
                    'kategori'           => $data['kategori'], // Enum WAJIB / KHUSUS[cite: 1]
                    'tipe_ukuran'        => $data['tipe_ukuran'], // Enum HURUF / ANGKA / UNIVERSAL[cite: 1]
                    'merk_rekomendasi'   => $data['merk_rekomendasi'],
                    'spesifikasi_teknis' => 'Spesifikasi standar industri untuk ' . $data['jenis_apd'],
                    'ukuran_tersedia'    => $data['ukuran_tersedia'],
                    'standar_regulasi'   => 'SNI / ANSI / EN',
                    'stok_awal'          => $stokAwal, // Integer[cite: 1]
                    'digunakan'          => $digunakan, // Integer[cite: 1]
                    'rusak'              => $rusak, // Integer[cite: 1]
                    'reorder_point'      => 20, // Integer[cite: 1]
                    'harga_satuan'       => $data['harga_satuan'], // Decimal 14,2[cite: 1]
                    'supplier'           => 'PT. Safety Nusantara',
                    'masa_pakai'         => $data['masa_pakai'],
                    'terakhir_pengadaan' => Carbon::now()->subMonths(rand(1, 12))->format('Y-m-d'),
                    'keterangan'         => 'Data dummy seeder otomatis.',
                ]);

                // Pasangkan seluruh daftar Kode OK hanya pada Helm Safety (item pertama) agar tabel relasi terisi
                if ($isFirstItem) {
                    $dataInsertKodes = [];
                    foreach ($listKodeOk as $kode) {
                        $dataInsertKodes[] = [
                            'stok_apd_id' => $apd->id,
                            'kode_ok'     => $kode,
                            'created_at'  => Carbon::now(),
                            'updated_at'  => Carbon::now(),
                        ];
                    }
                    // Insert massal untuk efisiensi
                    StokApdKode::insert($dataInsertKodes);
                    $isFirstItem = false;
                }
            }

            DB::commit();
            $this->command->info('Berhasil! 17 jenis APD dan Kode OK telah dimasukkan ke database.');
        } catch (\Exception $e) {
            DB::rollBack();
            $this->command->error('Gagal menjalankan seeder: ' . $e->getMessage());
        }
    }
}
